#!/bin/bash
#

sudo apt install git gcc g++ meson ninja-build glslang-dev libglvnd-dev mesa-common-dev libx11-dev libxnvctrl-dev libdbus-1-dev libxkbcommon-dev cmake nlohmann-json3-dev libspdlog-dev glslang-tools gamescope -y 

git clone --recurse-submodules https://github.com/flightlessmango/MangoHud.git
cd MangoHud

meson build
ninja -C build install

cd ..
sudo rm -r MangoHud/

tee ~/.config/MangoHud/MangoHud.conf << EOF
################### File Generated by GOverlay ###################
fps_limit=75
toggle_fps_limit=F1

no_display

legacy_layout=false
gpu_stats
gpu_temp
gpu_power
gpu_text=GPU
cpu_stats
cpu_temp
cpu_color=DE0835
cpu_text=CPU
io_color=D8D8D8
vram
vram_color=4FB830
ram
ram_color=DE0835
fps
engine_color=3A8623
gpu_color=4FB830
wine_color=3A8623
frame_timing=1
frametime_color=4FB830
media_player_color=3A8623
table_columns=3
background_alpha=0.4
font_size=24

background_color=020202
position=top-left
text_color=D8D8D8
round_corners=0
#GOVERLAY_THEME=amdnvidia
toggle_hud=Shift_R+F12
toggle_logging=Shift_L+F2
upload_log=F5
output_folder=/home/assem
media_player_name=spotify
EOF

sudo tee -a /etc/environment <<EOF
MANGOHUD=1
EOF
