#!/bin/bash

# Update package lists
sudo apt update

# Install libaio bec its needed
sudo apt-get install libaio1
  
# Add the MySQL repository
wget -q https://dev.mysql.com/get/mysql-apt-config_0.8.26-1_all.deb
sudo apt install ./mysql-apt-config_*_all.deb
sudo apt update

# Install MySQL server package
sudo apt install mysql-server

# Remove downloaded package (optional)
rm -f ./mysql-apt-config_*_all.deb

# Secure MySQL installation (prompts for password)
sudo mysql_secure_installation

echo "MySQL installation complete!"
